### ISSUE TITLE
throw error with binary

### ISSUE THREAD

**Issue by gerroon** [OwenRay/Remote-MediaServer#44]
Hi

I am getting the error below on Debian Buster x64 

```

./remote-mediaserver-linux                                                                                                 ⏎
running on platform: linux
downloading ffmpeg
chdir /home/USER/.remote/
2018-12-08T00:13:15.082Z 'starting http server'
koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md ../../../snapshot/Remote-MediaServer/backend/HttpServer.js:0:0
pkg/prelude/bootstrap.js:1176
      throw error;
      ^

Error: Cannot find module '/snapshot/Remote-MediaServer/node_modules/ed25519-supercop/prebuilds/linux-x64/node-57.node'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:545:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1278:46)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:594:17)
    at Module.require (pkg/prelude/bootstrap.js:1157:31)
    at require (internal/module.js:11:18)
    at load (/snapshot/Remote-MediaServer/node_modules/node-gyp-build/index.js:13:10)
    at Object.<anonymous> (/snapshot/Remote-MediaServer/node_modules/ed25519-supercop/index.js:1:103)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (module.js:661:10)
    at Module.load (module.js:563:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:594:17)
    at Module.require (pkg/prelude/bootstrap.js:1157:31)
    at require (internal/module.js:11:18)
```

**Comment by OwenRay** [comment]
Whoops, it seems the linux build packages a windows binary of ed25519-supercop
Will fix that momentarily

**Comment by gerroon** [comment]
shit happens, no problem

**Comment by OwenRay** [comment]
Is working properly now, latest binaries are attached to the release

**Comment by gerroon** [comment]
Thanks, how do I set custom ports?

**Comment by OwenRay** [comment]
Under settings, see the advanced checkbox. This will enable port and host configuration. Don't forget to hit the save button after your changes;)
